import type { Metadata } from "next";
import localFont from "next/font/local";
import { ThemeProvider } from "./components/theme-provider";
import { I18nProvider } from "./components/i18n-provider";
import { Suspense } from "react";
import { LoadingFallback } from "./components/LoadingFallback";
import "./globals.css";
import { LanguageProvider } from "./components/language-provider";
import Navbar from "./components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  return (
    <html lang={lang} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LanguageProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <I18nProvider>
              <div className="max-w-7xl mx-auto px-4 min-h-screen dark:bg-transparent transition-colors">
                <Navbar />
                <Suspense fallback={<LoadingFallback />}>
                  {children}
                </Suspense>
              </div>
            </I18nProvider>
          </ThemeProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
